// src/lib/components/Main/FAQ.svelte
<div class="py-6 sm:py-8 lg:py-12">
    <div class="mx-auto max-w-screen-xl px-4 md:px-8">
      <!-- text - start -->
      <div class="mb-10 md:mb-16">
        <h2 class="mb-4 text-center text-2xl font-bold text-transparent bg-clip-text leading-12 bg-gradient-to-r from-teal-200 to-lime-200 md:mb-6 lg:text-3xl">Frequently asked questions</h2>
        <p class="mx-auto max-w-screen-md text-center text-gray-300 md:text-lg">Browse Our FAQ Section for Insightful Information on Our Decentralized Cybersecurity Platform.</p>
      </div>
      <!-- text - end -->
  
      <div class="grid gap-4 sm:grid-cols-2 md:gap-8">

        <!-- question - start -->
        <div class="rounded-lg bg-black p-5">
          <div class="mb-4 flex items-center justify-between gap-4 border-b pb-4 border-green-200">
            <h3 class="font-semibold text-green-200 sm:text-lg md:text-xl">Is NetSepio safe to use?</h3>
          </div>
          <p class="text-gray-300">Yes, NetSepio is a highly secure platform that uses advanced blockchain technology to provide the best protection against scams and malware. Your personal information and digital assets are always safe and secure with NetSepio.</p>
        </div>
        <!-- question - end -->

        <!-- question - start -->
        <div class="rounded-lg bg-black p-5">
            <div class="mb-4 flex items-center justify-between gap-4 border-b pb-4 border-green-200">
              <h3 class="font-semibold text-green-200 sm:text-lg md:text-xl">What features does the NetSepio web app offer?</h3>
            </div>
            <p class="text-gray-300">The NetSepio web app allows users to read and delete their reviews. This feature provides users with control over their contributions to the community-driven approach to internet safety.</p>
        </div>
        <!-- question - end -->
  
        <!-- question - start -->
        <div class="rounded-lg bg-black p-5">
          <div class="mb-4 flex items-center justify-between gap-4 border-b pb-4 border-green-200">
            <h3 class="font-semibold text-green-200 sm:text-lg md:text-xl">What is the Web3 Archive feature in NetSepio?</h3>
          </div>
          <p class="text-gray-300">NetSepio's Web3 Archive feature archives reviews of websites/domains into IPFS, ensuring that users can always view their favorite content even if they are deleted. This feature ensures that important content is not lost, even if websites are taken down.</p>
        </div>
        <!-- question - end -->
  
        <!-- question - start -->
        <div class="rounded-lg bg-black p-5">
          <div class="mb-4 flex items-center justify-between gap-4 border-b pb-4 border-green-200">
            <h3 class="font-semibold text-green-200 sm:text-lg md:text-xl">How do I report a website for having unsafe content?</h3>
          </div>
          <p class="text-gray-300">You can report a website for having unsafe content by using the NetSepio browser extension. Simply click on the "Report Website" button and provide details about the website and the type of content that you find unsafe.</p>
        </div>
        <!-- question - end -->

        <!-- question - start -->
        <div class="rounded-lg bg-black p-5">
            <div class="mb-4 flex items-center justify-between gap-4 border-b pb-4 border-green-200">
                <h3 class="font-semibold text-green-200 sm:text-lg md:text-xl">Can I use NetSepio to protect my online privacy?</h3>
            </div>
            <p class="text-gray-300">Yes, NetSepio offers various platform features like VPN, Storage, and SSI that allow you to protect your online privacy. With our VPN service, you can browse the internet anonymously and securely. Our Storage feature lets you store and share files securely, and our SSI feature ensures that your personal information is safe and secure.</p>
        </div>
        <!-- question - end -->

        <!-- question - start -->
        <div class="rounded-lg bg-black p-5">
            <div class="mb-4 flex items-center justify-between gap-4 border-b pb-4 border-green-200">
              <h3 class="font-semibold text-green-200 sm:text-lg md:text-xl">How does NetSepio's NFT reward system work?</h3>
            </div>
            <p class="text-gray-300">Creating a review about a website/domain on NetSepio browser extension rewards users with a unique NFT. The review is also archived into IPFS for future reference. This reward system incentivizes users to contribute to the community-driven approach to internet safety without having to spend any gas or transaction fees.</p>
        </div>
        <!-- question - end -->
      </div>
    </div>
  </div>

// src/pages/Faq.jsx
import React, { useState } from "react";
import NavBar from "../components/NavBar";
import Footer from "../components/Footer";
import "../styles/Faq.css";

const faqData = [
  {
    question: "Is NetSepio safe to use?",
    answer:
      "Yes, NetSepio is a highly secure platform that uses advanced blockchain technology to provide the best protection against scams and malware. Your personal information and digital assets are always safe and secure with NetSepio.",
  },
  {
    question: "What features does the NetSepio web app offer?",
    answer:
      "The NetSepio web app allows users to read and delete their reviews and also search for other website reviews. This feature provides users with control over their contributions to the community-driven approach to internet safety.",
  },
  {
    question: "Can I use NetSepio to protect my online privacy?",
    answer:
      "Yes, NetSepio offers various platform features like VPN, and SSI that allow you to protect your online privacy. With our VPN service, you can browse the internet anonymously and securely. From real-time threat detection to proactive measures against cyber threats, NetSepio provides a comprehensive solution to protect your online privacy effectively.",
  },
  {
    question: "How does NetSepio differ from other cybersecurity platforms?",
    answer:
      "NetSepio is a decentralized review management system that combines the power of blockchain with cybersecurity to provide the best protection against scams and malware. Our platform offers unique features like NFT for sharing your thoughts on websites, an archive of reviews on IPFS, and community-driven decision-making for creating lists of unsafe websites.",
  },
  {
    question: "What are the benefits of using the NetSepio Crypto Wallet?",
    answer:
      "The NetSepio Crypto Wallet is a secure, multi-chain-supported crypto wallet that lets you send and receive coins and ERC20 tokens. With our Crypto Wallet, you can manage all your digital assets in one secure location, making it easy and convenient to trade and invest in cryptocurrencies. Additionally, the NetSepio Crypto Wallet supports multiple chains, ensuring that all your digital assets are safe and secure.",
  },
];

const FAQ = () => {
  const [openIndex, setOpenIndex] = useState(null);

  const toggleFAQ = (index) => {
    setOpenIndex(openIndex === index ? null : index);
  };
  return (
    <div className="faq-page">
      <NavBar />
      <div className="faq-content">
        <h1 className="faq-title">FAQ's</h1>
        <h3 className="faq-subtitle">Frequently Asked Questions</h3>
        <div className="faq-container">
          {faqData.map((item, index) => (
            <div key={index} className="faq-item">
              <button className="faq-question" onClick={() => toggleFAQ(index)}>
                <span>{item.question}</span>
                <span className="faq-icon">
                  {openIndex === index ? "−" : "+"}
                </span>
              </button>
              {openIndex === index && (
                <div className="faq-answer">{item.answer}</div>
              )}
            </div>
          ))}
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default FAQ;
